application: go-advent-calendar
version: 1
runtime: go
api_version: go1

instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 1m

skip_files:
- calendar/
- config/
- entry/
- router/
- store/

handlers:
- url: /css
  static_dir: static/css

- url: /.*
  script: _go_app

env_variables:
  CALENDAR_NAME: Advent Calendar
  CALENDAR_YEAR_MIN: 2014
  CALENDAR_YEAR_MAX: 2099
  CALENDAR_LOCATION: Asia/Tokyo
  #IP_WHITE_LIST: 127.0.0.1 ::1
